class AddConstraintOnTickets1 < ActiveRecord::Migration[6.0]
  def change
    execute "ALTER TABLE TICKETS ADD CONSTRAINT TICKETS_CK2 CHECK (TOTAL_QUANTITY > 0)"
    execute "ALTER TABLE TICKETS ADD CONSTRAINT TICKETS_CK3 CHECK (TICKET_PRICE >= 0)"
    execute "ALTER TABLE TICKETS ADD CONSTRAINT TICKETS_CK4 CHECK (FEES_PER_TICKET >= 0)"
    execute "ALTER TABLE TICKETS ADD CONSTRAINT TICKETS_CK5 CHECK (ACTUAL_TICKET_PRICE >= 0)"
    execute "ALTER TABLE TICKETS ADD CONSTRAINT TICKETS_CK6 CHECK (ORGANIZER_PAYOUT_PER_TICKET >= 0)"
  end
end
